FORMAT: 1A

# Vanhack-calendar-api

## POST /api/auth/login
+ Request (application/json)
  ```JSON
  { "username": "john.candidate@example.com", "password": "john.candidate" }
  ```
+ Response 200

## GET /api/events
+ Response 200
  + Body
      ```
      { "message": "Hello from Firebase" }
      ```
